

#CocoPods 远程共有库
source  'https://github.com/CocoaPods/Specs.git'



# Uncomment the next line to define a global platform for your project
platform :ios, ‘9.0’
use_modular_headers!
# use_frameworks!
target 'TestDemo' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # Pods for TestDemo
  #pod 'CryptoSwift'
  use_frameworks!
  pod 'UICKeyChainStore' #存钥匙链
  #keystore 相关
  pod 'BigInt'
  pod 'CryptoSwift'#, '~> 0.10.0' 加密库
  pod 'TrezorCrypto', inhibit_warnings: true
  pod 'TrustCore', inhibit_warnings: true
  pod 'SwiftLint'
  # pod 'SwiftLint'
  #Private
#  pod 'LTCategorys'

end
